config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'home', to: 'static_pages#home'
    get 'users', to: 'users#index'
    resources :users, only: [:update, :destroy]
    resources :categories do
      resources :words
    end
  end

  

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/categories', to: 'categories#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :words, only: [:index]

  resources :lessons do
    resources :answers
  end

end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices, allow_destroy: true
  has_many :answers, dependent: :destroy
  validates :content, presence: true
  validate :has_one_correct_answer
  validate :has_unique_choices

  def correct_answer
    choices.find_by(correct: true).content
  end

  def has_one_correct_answer
    if choices.select { |choice| choice.correct? }.count != 1
      return errors.add :base, "Must have one correct choice!"
    end
  end
  
  def has_unique_choices
    if choices.uniq{ |choice| choice.content }.count < choices.length
      return errors.add :base, "Must have unique choices!"
    end
  end 

end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @word = @category.words.build
    3.times { @word.choices.build }
  end

  def create
    @category = Category.find(params[:category_id])
    @word = @category.words.build(word_params)

    if @word.save
      flash[:success] = "Successfully created!"
      redirect_to admin_category_words_url
    else
      render 'new'
    end
  end

  def index
    @category = Category.find(params[:category_id])
    @words = @category.words.paginate(page: params[:page], per_page: 10)    
  end

  def edit
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
  
  end
  
  def update
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
    @word.update(word_params)
    if @word.update(word_params)
      flash[:success] = "Successfully Updated!"
      redirect_to  admin_category_words_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
    @word.destroy
    flash[:success] = "Successfully Deleted!"
    redirect_to  admin_category_words_url
  end

  private
    def word_params
      params.require(:word).permit(:content, choices_attributes: [:id, :content, :correct])
    end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @lessons = current_user.lessons
    @answers = current_user.answers.paginate(page: params[:page], per_page: 10)
  end
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @category, @word] do |f| %>
<%= render 'shared/error_messages', object: f.object %>
    <div class="form-group my-3">
        <strong><%= label_tag "Word:" %></strong>
        <%= f.text_field :content, class: "form-cotrol" %>
    </div>
    <div class="form-group">
        <%= label_tag "★Choices★" %>
        <%= f.fields_for :choices do |choice| %>
            <%= choice.text_field :content, class: "form-control" %>
            <%= choice.check_box :correct, class: "d-inline" %>
            <p class="d-inline">This is the answer!</p> 
        <% end %>   

    <% if @word.content %>
        <%= f.submit 'Edit words', class:"btn btn-block btn-outline-success mt-3" %>
    <% else %>
        <%= f.submit 'Cretate new words', class:"btn btn-block btn-outline-danger mt-3" %>
    <% end %>
<% end  %>
<%= link_to("Back to Words List", admin_category_words_path, class: "btn btn-block btn-blue mb-3") %>

app/views/admin/words/edit.html.erb
<div class="container mt-5">
    <div class="text-center">
       <h1>Edit Words</h1>
    </div>            
    <div class="row">
        <div class="col-6 mx-auto">
            <%= render 'admin/words/form' %>
        </div>
    </div>
</div>

app/views/admin/words/index.html.erb
<div class="container mt-5">
    <div class="text-center">
        <h1>All Words</h1>

        <%= link_to "Create New Word", new_admin_category_word_path, class: "btn btn-pink my-3"%>

        <div class="paginate pagination justify-content-center my-3">
            <%= will_paginate :previous_label => '<', :next_label => '>' %>
        </div>

        <div class="row">
            <% @words.each do |word| %>
                <div class="col-md-6">
                    <section>
                        <div class="card text-left my-3">
                            <div class="card-header">
                                <div class="row">
                                    <div class="col-md-5">
                                        <small>Title:</small>
                                        <%=  word.content %>
                                    </div>
                                    <div class="col-md-7">
                                        <%= link_to "Edit", edit_admin_category_word_path(@category, word), class: "btn btn-sm btn-outline-success mr-3 w-25" %>
                                        <%= link_to "Delete", admin_category_word_path(@category, word),
                                            method: :delete,
                                            class: "btn btn-sm btn-outline-danger mr-3 w-25",
                                            data: {title: 'Confirmation',
                                                    confirm: 'Are you sure you want to delete?',
                                                    commit: 'Sure!',
                                                    cansel: 'No...'} %>
                                    </div>
                                </div>                                    
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-5 text-left">
                                        <p>Answer : <%= word.correct_answer %></p>
                                    </div>
                                    <div class="col-md-7 text-left">
                                        <% word.choices.each do |choice| %>
                                            <small>Choice : </small>
                                            <%= choice.content %>
                                            <br>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                        </div>                        
                    </section>
                </div>
            <% end %>
        </div>

        <div class="paginate pagination justify-content-center my-3">
            <%= will_paginate :previous_label => '<', :next_label => '>' %>
        </div>

        <%= link_to("Back to Category List", admin_categories_path, class: "btn btn-blue mx-auto mb-3") %>
    </div>
</div>

app/views/admin/words/new.html.erb
<div class="container mt-5">
    <div class="text-center">
       <h1>Create New Words</h1>
    </div>            
    <div class="row">
        <div class="col-6 mx-auto">
            <%= render 'form' %>
        </div>
    </div>
</div>