config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'home', to: 'static_pages#home'
    get 'users', to: 'users#index'
    resources :users, only: [:update, :destroy]
    resources :categories do
      resources :words
    end
  end

  

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/categories', to: 'categories#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :words, only: [:index]

  resources :lessons do
    resources :answers
  end

end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }

  validates :name, presence: true, length: { minimum: 2, maximum: 30 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  validates :email, presence: true, length: {minimum: 10, maximum: 30 },
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 4 }, allow_nil: true

  mount_uploader :image, ImageUploader

  has_many :active_relationships, class_name: "Relationship",
          foreign_key: "follower_id",
          dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  
  has_many :passive_relationships, class_name:  "Relationship",
          foreign_key: "followed_id",
          dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :lessons, dependent: :destroy

  has_many :answers, through: :lessons

  has_many :categories, through: :lessons

  has_many :activities, dependent: :destroy
  


  def active_relationships
    Relationship.where(follower_id: id)
  end

  def passive_relationships
    Relationship.where(followed_id: id)
  end

  def followers
    ids = passive_relationships.pluck(:follower_id)
    User.where(id: ids)
  end
  
  def following
    ids = active_relationships.pluck(:followed_id)
    User.where(id: ids)
  end

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーのフォロー解除
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  def relationship(other_user)
    active_relationships.find_by(
      followed_id: other_user.id
    )
  end

  def lesson_taken(cat_id)
    lesson = lessons.find_by(category_id: cat_id)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(admin: true)
    
    redirect_to admin_users_url
  end

  def destroy
    @user = User.find(params[:id])
    @user.update(admin: false)

    redirect_to admin_users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = "Welcome to E-learning page!!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities.paginate(page: params[:page], per_page: 10)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(users_params)
      flash[:success] = "Successfully Updated!"
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end

  def following
    @user = User.find(params[:id])
    @title = "Following"
    @users = @user.following.paginate(page: params[:page])
    render "users/follow"
  end

  def followers
    @user = User.find(params[:id])
    @title = "Followers"
    @users = @user.followers.paginate(page: params[:page])
    render "users/follow"
  end

  def users_params
    params.require(:user).permit(:name, :email, :password, :password_digest, :image)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_image(user, classes)
    @image = user.image
    if @image.present?
      @image_user = image_tag(@image.url, class: classes)
    else
      @image_user = image_tag("default.jpeg", class: classes)
    end
  end
end

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
    <% unless current_user.relationship(@user) %>
        <%= button_to "Follow", relationships_path,
                            params: {followed_id: @user.id},
                            class: "btn btn-sm btn-success mt-3" %>
    <% else %>
        <%= button_to "Unfollow", relationship_path(current_user.relationship(@user)),
                                        method: :delete,
                                        class: "btn btn-sm btn-danger mt-3" %>
    <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

<%= render 'shared/error_messages', object: f.object %>
    <form class="container">
        <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :email %><br>
            <%= f.email_field :email, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :password %><br>
            <%= f.password_field :password, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation %><br>
            <%= f.password_field :password_confirmation, class:"form-control" %>
        </div>

        <% if signed_in? %>
            <div class="form-group">
                <%= f.label :image %><br>
                <%= f.file_field :image %>
            </div>
            <div class="form-group">
                <%= f.submit "Edit Your Account Here", class:"btn btn-block btn-green mt-3" %>
            </div>
        <% else %>
            <div class="form-group">
                <%= f.submit "Create New Account Here", class:"btn btn-block btn-pink mt-3" %>
            </div>
        <% end %>


    </form>
<% end %>

app/views/users/edit.html.erb
<div class="container mt-5">
    <div class="text-center">
        <h1>Edit</h1>
        <p>Edit your information here.</p>
    </div>            
    <div class="row">
        <div class="col-6 mx-auto">
            <%= render 'users/form' %>
        </div>
    </div>
</div>

app/views/users/follow.html.erb
<div class="row container mt-5 mx-auto">
    <aside class="col-md-4 text-center">
        <div class="card text-center">
            <div class="card-header">
                User Information
            </div>

            <div class=card-body>
                <%= render 'shared/user_info'  %>
            </div>
        </div>
    </aside>

    <div class="col-md-8">
        <div class="card">
            <div class="card-header text-center">
                <%= @title %>
            </div>
            <div class="card-body">
                <% @users.each do |user| %>
                    <div class="media m-3">
                        <%= user_image(user, "smaller-image-size") %>
                        <div class="media-body ml-3 my-auto">
                            <h5><%= link_to user.name, user, :style=>"color: #20b2aa;" %></h5>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="paginate pagination justify-content-center my-3">
            <%= will_paginate :previous_label => '<', :next_label => '>' %>
        </div>
    </div>
</div>

app/views/users/home_feed.html.erb
<div class="row container mt-5 mx-auto">
    <aside class="col-md-4 text-center">
        <div class="card text-center">
            <div class="card-header">
                User Information
            </div>

            <div class=card-body>
                <%= user_image(current_user, "image-size") %>
                <h3 class="my-2"><%= current_user.name %></h3>
                <%= current_user.email %>
                <br>
                <%= link_to("Update Profile", edit_user_path(current_user), class: "btn btn-outline-primary my-2") %>
                <% if current_user.admin? %>
                    <%= link_to "Admin Page", admin_home_path, class: "btn btn-outline-success my-2" %>
                <% end %>

                <hr>
                <div class="row">
                    <div class="col">
                        <h5>
                            <%= link_to current_user.active_relationships.count, following_user_path(current_user), :style=>"color: #20b2aa;" %>
                        </h5>
                        <small>following</small>    
                    </div>
                    <div class="col">
                        <h5>
                            <%= link_to current_user.passive_relationships.count, followers_user_path(current_user), :style=>"color: #20b2aa;" %>
                        </h5>
                        <small>followers</small>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <h5>
                    <%= link_to current_user.answers.count, words_path, :style=>"color: #20b2aa;" %>
                </h5>
                <small>words learned</small>
            </div>
        </div>
    </aside>

    <div class="col-md-8">
        <div class="card ">
            <div class="card-header text-center">
                Activity Feeds
            </div>
            <div class="card-body mb-2">
                <%= render 'shared/feeds' %>
            </div>
        </div>
        <div class="paginate pagination justify-content-center my-3">
            <%= will_paginate @activities, :previous_label => '<', :next_label => '>' %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container mt-5">
    <div class="text-center">
        <h1>All Users</h1>

        <div class="paginate pagination justify-content-center mb-3">
            <%= will_paginate :previous_label => '<', :next_label => '>' %>
        </div>

        <div class="row text-left">
            <% @users.each do |user| %>
                <div class="col-md-6">
                    <section class="section_color">
                        <div class="border_line">
                            <div class="row">
                                <div class="col-md-4">
                                    <%= user_image(user, "index-image-size") %>
                                </div>
                                <div class="col-md-5 my-auto">
                                    <%= link_to user.name, user, :style=>"color: #20b2aa;" %>
                                </div>                    
                            </div>
                        </div>
                    </section>
                </div>
            <% end %>
        </div>

        <div class="paginate pagination justify-content-center my-3">
            <%= will_paginate :previous_label => '<', :next_label => '>' %>
        </div>

        <%= link_to("Back to Home", root_path, class: "btn btn-blue mx-auto my-3") %>        
    </div>
</div>

app/views/users/new.html.erb
<div class="container mt-5">
    <div class="text-center">
        <h1>Signup</h1>
        <p>Join us for free!!</p>
    </div>            
    <div class="row">
        <div class="col-6 mx-auto">
            <%= render 'users/form' %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row container mt-5 mx-auto">
    <aside class="col-md-4 text-center">
        <div class="card text-center">
            <div class="card-header">
                User Information
            </div>

            <div class=card-body>
                <%= render 'shared/user_info'  %>
            </div>
        </div>
    </aside>

    <div class="col-md-8">
        <div class="card activity">
            <div class="card-header text-center">
                Activity Feeds
            </div>
            <div class="card-body">
                <%= render 'shared/feeds' %>
            </div>
        </div>
        <div class="paginate pagination justify-content-center my-3">
            <%= will_paginate @activities, :previous_label => '<', :next_label => '>' %>
        </div>
    </div>
</div>