config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'home', to: 'static_pages#home'
    get 'users', to: 'users#index'
    resources :users, only: [:update, :destroy]
    resources :categories do
      resources :words
    end
  end

  

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/categories', to: 'categories#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :words, only: [:index]

  resources :lessons do
    resources :answers
  end

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action, polymorphic: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :word
  belongs_to :choice
  belongs_to :lesson
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  def number_of_words
    Word.where(category_id: id)
  end
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
  has_many :answers, dependent: :destroy
  validates :content, presence: true, length: { minimum: 2, maximum: 30 }
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :words, through: :answers
  has_many :choices, through: :answers
  has_one :activity, as: :action

  def next_word
    (category.words - words).first
  end

  def lesson_results
    choices.where(correct: true).count
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
  has_one :activity, as: :action

  after_create :relationship_activity
  
  def relationship_activity
    create_activity(user: follower)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }

  validates :name, presence: true, length: { minimum: 2, maximum: 30 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  validates :email, presence: true, length: {minimum: 10, maximum: 30 },
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 4 }, allow_nil: true

  mount_uploader :image, ImageUploader

  has_many :active_relationships, class_name: "Relationship",
          foreign_key: "follower_id",
          dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  
  has_many :passive_relationships, class_name:  "Relationship",
          foreign_key: "followed_id",
          dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :lessons, dependent: :destroy

  has_many :answers, through: :lessons

  has_many :categories, through: :lessons

  has_many :activities, dependent: :destroy
  


  def active_relationships
    Relationship.where(follower_id: id)
  end

  def passive_relationships
    Relationship.where(followed_id: id)
  end

  def followers
    ids = passive_relationships.pluck(:follower_id)
    User.where(id: ids)
  end
  
  def following
    ids = active_relationships.pluck(:followed_id)
    User.where(id: ids)
  end

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーのフォロー解除
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  def relationship(other_user)
    active_relationships.find_by(
      followed_id: other_user.id
    )
  end

  def lesson_taken(cat_id)
    lesson = lessons.find_by(category_id: cat_id)
  end

end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices, allow_destroy: true
  has_many :answers, dependent: :destroy
  validates :content, presence: true
  validate :has_one_correct_answer
  validate :has_unique_choices

  def correct_answer
    choices.find_by(correct: true).content
  end

  def has_one_correct_answer
    if choices.select { |choice| choice.correct? }.count != 1
      return errors.add :base, "Must have one correct choice!"
    end
  end
  
  def has_unique_choices
    if choices.uniq{ |choice| choice.content }.count < choices.length
      return errors.add :base, "Must have unique choices!"
    end
  end 

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    # ここで、次に学ぶwordを表示する
    @answer = Answer.new
    @lesson = Lesson.find(params[:lesson_id])
    @category = Category.find_by(id: @lesson.category_id)

    if @lesson.next_word.nil?
      @lesson.update(result: @lesson.lesson_results)
      @lesson.create_activity(user: current_user)
      redirect_to lesson_url(@lesson)
    end
  end

  def create
    # ここで、ユーザーが選択した回答をDBに保存する
    @lesson = Lesson.find(params[:lesson_id])
    @answer = @lesson.answers.build(answer_params)
    if @answer.save
      redirect_to new_lesson_answer_url(@lesson)
    end
  end

  private
    def answer_params
      params.require(:answer).permit(:word_id, :choice_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = "Welcome to E-learning page!!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities.paginate(page: params[:page], per_page: 10)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(users_params)
      flash[:success] = "Successfully Updated!"
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end

  def following
    @user = User.find(params[:id])
    @title = "Following"
    @users = @user.following.paginate(page: params[:page])
    render "users/follow"
  end

  def followers
    @user = User.find(params[:id])
    @title = "Followers"
    @users = @user.followers.paginate(page: params[:page])
    render "users/follow"
  end

  def users_params
    params.require(:user).permit(:name, :email, :password, :password_digest, :image)
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @lessons = current_user.lessons
    @answers = current_user.answers.paginate(page: params[:page], per_page: 10)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def signed_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_image(user, classes)
    @image = user.image
    if @image.present?
      @image_user = image_tag(@image.url, class: classes)
    else
      @image_user = image_tag("default.jpeg", class: classes)
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        This form contains errors.
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg|  %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/shared/_feeds.html.erb
<% if @activities.any? %>
    <% @activities.each do |activity| %>
        <div class="row">
            <div class="col-md-3">
                <%= user_image(activity.user, "smaller-image-size") %>
            </div>
            <div class="col-md-9 my-auto">
                <% if activity.action_type == "Lesson" %>
                    <% if activity.user == current_user %>
                        <p><%= link_to "You", root_path, :style=>"color: #20b2aa;" %> learned 
                            <%= activity.action.result %> of 
                            <%= activity.action.category.words.count %> in 
                            <%= link_to activity.action.category.title, lesson_path(id: activity.action.id), :style=>"color: #20b2aa;" %></p>
                    <% else %>
                        <p><%= link_to activity.user.name, user_path(activity.user), :style=>"color: #20b2aa;" %> learned 
                            <%= activity.action.result %> of <%= activity.action.category.words.count %> in 
                            <%= link_to activity.action.category.title, lesson_path(id: activity.action.id), :style=>"color: #20b2aa;" %></p>
                    <% end %>
                <% else %>
                    <% followed_user = User.find_by(id: activity.action.followed_id) %>
                    <% if activity.user == current_user %>
                        <p><%= link_to "You", root_path, :style=>"color: #20b2aa;" %> followed <%= link_to followed_user.name, user_path(followed_user), :style=>"color: #20b2aa;" %></p>
                    <% else %>
                        <% if followed_user == current_user %>
                            <p><%= link_to activity.user.name, user_path(activity.user), :style=>"color: #20b2aa;" %> followed <%= link_to "You", root_path, :style=>"color: #20b2aa;"%></p>
                        <% else %>
                            <p><%= link_to activity.user.name, user_path(activity.user), :style=>"color: #20b2aa;"%> followed <%= link_to followed_user.name, user_path(followed_user), :style=>"color: #20b2aa;"%></p>
                        <% end %>
                    <% end %>
                <% end %>
                <span class="timestamp text-secondary font">
                    <small><%= time_ago_in_words(activity.created_at) %> ago.</small>
                </span>
            </div>
        </div>
    <% end %>
<% else %>
    <h5>Nothing to show</h5>
<% end %>

app/views/shared/_user_info.html.erb
<%= user_image(@user, "image-size") %>
<h3 class="my-2"><%= link_to @user.name, user_path(@user), :style=>"color: #20b2aa;" %></h3>
<%= @user.email %>
<%= render 'follow_form' %>
<br>
<% if current_user.admin? && @user == current_user %>
    <%= link_to "Admin Page", admin_home_path, class: "btn btn-outline-primary my-2" %>
<% end %>
<hr>
<div class="row">
    <div class="col">
        <h5>
            <%= link_to @user.active_relationships.count, following_user_path(@user), :style=>"color: #20b2aa;" %>
        </h5>
        <small>following</small>    
    </div>
    <div class="col">
        <h5>
            <%= link_to @user.passive_relationships.count, followers_user_path(@user), :style=>"color: #20b2aa;" %>
        </h5>
        <small>followers</small>
    </div>
</div>