config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'home', to: 'static_pages#home'
    get 'users', to: 'users#index'
    resources :users, only: [:update, :destroy]
    resources :categories do
      resources :words
    end
  end

  

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/categories', to: 'categories#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :words, only: [:index]

  resources :lessons do
    resources :answers
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  def number_of_words
    Word.where(category_id: id)
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      flash[:success] = "You successfully saved a new category!!"
      redirect_to admin_categories_url
    else
      render 'new'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(categories_params)
    if @category.update(categories_params)
      flash[:success] = "Successfully Updated!"
      redirect_to  admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    if @category.destroy
      flash[:success] = "Successfully Deleted!"
      redirect_to  admin_categories_url
    else
      render 'edit'
    end
  end

  def categories_params
    params.require(:category).permit(:title, :description)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 10)
    @status = params[:status]

      if @status == "1"
        @categories = current_user.categories.paginate(page: params[:page], per_page: 10)
      elsif @status == "0"
        @categories = @categories.where.not(id: current_user.category_ids).paginate(page: params[:page], per_page: 10)
      end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
<%= render 'shared/error_messages', object: f.object %>
    <form class="container mx-auto">
        <div class="form-group">
            <%= f.label :title %><br>
            <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :description %><br>
            <%= f.text_area :description, class:"form-control" %>
        </div>
        <div class="form-group float-center">
            <% if @category.title %>
                <%= f.submit "Edit Category", class:"btn btn-block btn-green mt-3" %>
            <% else %>
                <%= f.submit "Create New Category", class:"btn btn-block btn-pink mt-3" %>
            <% end %>
        </div>
        <%= link_to("Back to Categories List", admin_categories_path, class: "btn btn-block btn-blue mx-auto mb-3") %>
    </form>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="container mt-5">
    <div class="text-center">
       <h1>Edit Category</h1>
    </div>            
    <div class="row">
        <div class="col-6 mx-auto">
            <%= render 'admin/categories/form' %>
        </div>
    </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container mt-5">
    <div class="text-center">
        <h1>All Categories</h1>

        <%= link_to "Create New Category", new_admin_category_path, class: "btn btn-pink my-3"  %>

        <div class="paginate pagination justify-content-center my-3">
            <%= will_paginate :previous_label => '<', :next_label => '>' %>
        </div>

        <div class="row">
            <% @categories.each do |category| %>
                <div class="col-md-6">
                    <section>
                        <div class="card text-left my-3">
                            <div class="card-header">
                                <small>Title:</small>
                                <%= link_to category.title, admin_category_words_path(category), :style=>"color: #20b2aa;" %>
                            </div>

                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-8">
                                        <small>Description:</small>
                                        <br>
                                        <%= category.description %>
                                    </div>
                                    <div class="col-md-4">
                                        <%= link_to "Edit", edit_admin_category_path(category), class: "btn btn-sm btn-outline-success mr-3" %>
                                        <%= link_to "Delete", admin_category_path(category),
                                            method: :delete,
                                            class: "btn btn-sm btn-outline-danger mr-3",
                                            data: {title: "Confirmation",
                                                    confirm: "Are you sure you want to delete?",
                                                    commit: "Sure!",
                                                    cancel: "No..."} %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            <% end %>
        </div>

        <div class="paginate pagination justify-content-center my-3">
            <%= will_paginate :previous_label => '<', :next_label => '>' %>
        </div>

        <%= link_to("Back to Admin Page", admin_home_path, class: "btn btn-blue mx-auto mb-3") %>
    </div>
</div>

app/views/admin/categories/new.html.erb
<div class="container mt-5">
    <div class="text-center">
       <h1>Create New Category</h1>
    </div>            
    <div class="row">
        <div class="col-6 mx-auto">
            <%= render 'admin/categories/form' %>
        </div>
    </div>
</div>